### ISSUE TITLE
Installing on OSX

### ISSUE THREAD

**Issue by cristian-frincu** [cmpute/pcl.py#7]
What are the requirements for installation on OSX?

Using just pip3, I get an error saying that I need XCode installed (XCode 10 is already installed)

Thank you

**Comment by cmpute** [comment]
Could you please post the detailed log? At least you should have pcl (C++), numpy and cython installed. In order to make cython available, a C/C++ compiler is needed. Maybe this is why it suggest you XCode.

**Comment by cmpute** [comment]
I will close the issue by now as no further information is provided :)
