### ISSUE TITLE
installation failed with missing files

### ISSUE THREAD

**Issue by llmpass** [cmpute/pcl.py#9]
I tried to install the package from src and got the following issue:

[ 94%] Building CXX object pcl/visualization/CMakeFiles/_visualization.dir/_visualization.cxx.o
In file included from /usr/include/python3.6m/numpy/ndarraytypes.h:1809:0,
                 from /usr/include/python3.6m/numpy/ndarrayobject.h:18,
                 from /usr/include/python3.6m/numpy/arrayobject.h:4,
                 from /home/luming/Downloads/pcl.py/_skbuild/linux-x86_64-3.6/cmake-build/pcl/visualization/_visualization.cxx:607:
/usr/include/python3.6m/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
/home/luming/Downloads/pcl.py/_skbuild/linux-x86_64-3.6/cmake-build/pcl/visualization/_visualization.cxx:629:10: fatal error: pcl/visualization/area_picking_event.h: No such file or directory
 #include "pcl/visualization/area_picking_event.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
pcl/visualization/CMakeFiles/_visualization.dir/build.make:67: recipe for target 'pcl/visualization/CMakeFiles/_visualization.dir/_visualization.cxx.o' failed
make[2]: *** [pcl/visualization/CMakeFiles/_visualization.dir/_visualization.cxx.o] Error 1
CMakeFiles/Makefile2:355: recipe for target 'pcl/visualization/CMakeFiles/_visualization.dir/all' failed
make[1]: *** [pcl/visualization/CMakeFiles/_visualization.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/luming/.local/lib/python3.6/site-packages/skbuild/setuptools_wrap.py", line 577, in setup
    cmkr.make(make_args, env=env)
  File "/home/luming/.local/lib/python3.6/site-packages/skbuild/cmaker.py", line 482, in make
    os.path.abspath(CMAKE_BUILD_DIR())))

An error occurred while building with CMake.
  Command:
    "cmake" "--build" "." "--target" "install" "--config" "Release" "--"
  Source directory:
    /home/luming/Downloads/pcl.py
  Working directory:
    /home/luming/Downloads/pcl.py/_skbuild/linux-x86_64-3.6/cmake-build

Any ideas why?

**Comment by cmpute** [comment]
Could you please share your system version and PCL version? I think the missing header file may be missing from old versions

**Comment by GoogleMike** [comment]
> I tried to install the package from src and got the following issue:
> 
> [ 94%] Building CXX object pcl/visualization/CMakeFiles/_visualization.dir/_visualization.cxx.o
> In file included from /usr/include/python3.6m/numpy/ndarraytypes.h:1809:0,
> from /usr/include/python3.6m/numpy/ndarrayobject.h:18,
> from /usr/include/python3.6m/numpy/arrayobject.h:4,
> from /home/luming/Downloads/pcl.py/_skbuild/linux-x86_64-3.6/cmake-build/pcl/visualization/_visualization.cxx:607:
> /usr/include/python3.6m/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
> #warning "Using deprecated NumPy API, disable it by " 
> ^~~~~~~
> /home/luming/Downloads/pcl.py/_skbuild/linux-x86_64-3.6/cmake-build/pcl/visualization/_visualization.cxx:629:10: fatal error: pcl/visualization/area_picking_event.h: No such file or directory
> #include "pcl/visualization/area_picking_event.h"
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> pcl/visualization/CMakeFiles/_visualization.dir/build.make:67: recipe for target 'pcl/visualization/CMakeFiles/_visualization.dir/_visualization.cxx.o' failed
> make[2]: *** [pcl/visualization/CMakeFiles/_visualization.dir/_visualization.cxx.o] Error 1
> CMakeFiles/Makefile2:355: recipe for target 'pcl/visualization/CMakeFiles/_visualization.dir/all' failed
> make[1]: *** [pcl/visualization/CMakeFiles/_visualization.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2
> Traceback (most recent call last):
> File "/home/luming/.local/lib/python3.6/site-packages/skbuild/setuptools_wrap.py", line 577, in setup
> cmkr.make(make_args, env=env)
> File "/home/luming/.local/lib/python3.6/site-packages/skbuild/cmaker.py", line 482, in make
> os.path.abspath(CMAKE_BUILD_DIR())))
> 
> An error occurred while building with CMake.
> Command:
> "cmake" "--build" "." "--target" "install" "--config" "Release" "--"
> Source directory:
> /home/luming/Downloads/pcl.py
> Working directory:
> /home/luming/Downloads/pcl.py/_skbuild/linux-x86_64-3.6/cmake-build
> 
> Any ideas why?

Hi, I meet the same question as yours.
Have you solved it?

**Comment by cmpute** [comment]
As I cannot help with you without your information about your system, I'm closing the issue by now. Feel free to reopen it :)
